// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRyMMh4hStDuUR_ohBr3LwZUbjfW8CGX8',
    appId: '1:143355216435:web:905c1b80d1a8fc1317d946',
    messagingSenderId: '143355216435',
    projectId: 'tubes-mobile-73d32',
    authDomain: 'tubes-mobile-73d32.firebaseapp.com',
    storageBucket: 'tubes-mobile-73d32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiM_Xj1lRVEr0kfDFmlaJgstudd0eXdc0',
    appId: '1:143355216435:android:4c846ab594d9394417d946',
    messagingSenderId: '143355216435',
    projectId: 'tubes-mobile-73d32',
    storageBucket: 'tubes-mobile-73d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhYye7Bdcsz0uQVFuItjkuH3s2td4rYZ0',
    appId: '1:143355216435:ios:00652f5af5af988b17d946',
    messagingSenderId: '143355216435',
    projectId: 'tubes-mobile-73d32',
    storageBucket: 'tubes-mobile-73d32.appspot.com',
    iosClientId: '143355216435-jfcps8buop41hpo69kbgoaaojvhdpojt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesOcr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhYye7Bdcsz0uQVFuItjkuH3s2td4rYZ0',
    appId: '1:143355216435:ios:fe028bad53b282b517d946',
    messagingSenderId: '143355216435',
    projectId: 'tubes-mobile-73d32',
    storageBucket: 'tubes-mobile-73d32.appspot.com',
    iosClientId: '143355216435-2vfpv836bc35ql5j3esqqgsqtogloje7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesOcr.RunnerTests',
  );
}
